[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
user=vscode

[program:Xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x24
autostart=true
autorestart=true
priority=10
stderr_logfile=/tmp/xvfb.err.log
stdout_logfile=/tmp/xvfb.out.log

[program:xfce4]
command=/usr/bin/xfce4-session
environment=DISPLAY=":1",HOME="/home/vscode",USER="vscode"
user=vscode
autostart=true
autorestart=true
priority=20
startsecs=5
stderr_logfile=/tmp/xfce4.err.log
stdout_logfile=/tmp/xfce4.out.log

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -rfbport 5901 -passwd anzucloud
environment=DISPLAY=":1",HOME="/home/vscode",USER="vscode"
user=vscode
autostart=true
autorestart=true
priority=30
stderr_logfile=/tmp/x11vnc.err.log
stdout_logfile=/tmp/x11vnc.out.log

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5901
environment=HOME="/home/vscode",USER="vscode"
user=vscode
autostart=true
autorestart=true
priority=40
stderr_logfile=/tmp/novnc.err.log
stdout_logfile=/tmp/novnc.out.log