[supervisord]
nodaemon=false
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
directory=/tmp
childlogdir=/tmp

[program:Xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x24
autostart=true
autorestart=true
priority=10

[program:xfce4]
command=/usr/bin/xfce4-session
environment=DISPLAY=":1",HOME="/home/vscode",USER="vscode"
user=vscode
autostart=true
autorestart=true
priority=20

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -rfbport 5901 -passwdfile /home/vscode/.vnc/passwd
environment=DISPLAY=":1",HOME="/home/vscode",USER="vscode"
user=vscode
autostart=true
autorestart=true
priority=30

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5901
autostart=true
autorestart=true
priority=40